
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usersdb
  SPRING_DATASOURCE_USERNAME: user
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: "6379"
